language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly

before_script:
  - composer install

script:
  - vendor/bin/phpunit

git:
  depth: 5
